---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: documentation

platforms:
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[httpd::default]
      - recipe[httpd::ohai_httpd_modules]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
